# Generated by Django 3.2.16 on 2023-06-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
