# Generated by Django 3.2.16 on 2023-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0002_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=64)),
                ('news_text1', models.TextField(max_length=1024)),
                ('news_text2', models.TextField(max_length=1024)),
                ('news_text3', models.TextField(max_length=1024)),
                ('news_text4', models.TextField(max_length=1024)),
            ],
        ),
    ]
