# Generated by Django 3.2.16 on 2023-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_text1',
            field=models.TextField(max_length=1024, verbose_name='Текст 1'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text2',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Текст 2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text3',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Текст 3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text4',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Текст 4'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=64, verbose_name='Заголовок новости'),
        ),
    ]
